// authReducer
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// cartReducer
const LOAD_CART = 'LOAD_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const ADD_TO_CART = 'ADD_TO_CART';
const CLEAR_CART = 'CLEAR_CART';

export {
  LOGIN_SUCCESS,
  LOGOUT_SUCCESS,
  LOAD_CART,
  REMOVE_FROM_CART,
  ADD_TO_CART,
  CLEAR_CART
};
