// authReducer
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// cartReducer
const LOAD_CART = 'LOAD_CART';
const REMOVE_FROM_CART = 'REMOVE FROM CART';

export { LOGIN_SUCCESS, LOGOUT_SUCCESS, LOAD_CART, REMOVE_FROM_CART }
