// authReducer
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

// cartReducer
const LOAD_CART = 'LOAD_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const ADD_TO_CART = 'ADD_TO_CART';
const CLEAR_CART = 'CLEAR_CART';


// // checkoutReducer
const ON_SAVE_STEP_SUCCESS = 'ON_SAVE_STEP_SUCCESS';


// orderReducer
const LOAD_ORDER = 'LOAD_ORDER';
const LOAD_ERROR = 'LOAD_ERROR';
const COMPLETE_CHECKOUT = 'COMPLETE_CHECKOUT';
const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS';
const LOAD_COMPLETED_ORDERS = 'LOAD_COMPLETED_ORDERS';


// productsReducer
const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
const SELECT_PRODUCT_SUCCESS = 'SELECT_PRODUCT_SUCCESS';
const DESELECT_PRODUCT_SUCCESS = 'DESELECT_PRODUCT_SUCCESS';


export {
    LOGIN_SUCCESS,
    LOGOUT_SUCCESS,
    CREATE_USER_FAILURE,
    LOAD_CART,
    REMOVE_FROM_CART,
    ADD_TO_CART,
    CLEAR_CART,
    ON_SAVE_STEP_SUCCESS,
    LOAD_ORDER,
    LOAD_ERROR,
    COMPLETE_CHECKOUT,
    CONFIRM_ORDER_SUCCESS,
    LOAD_COMPLETED_ORDERS,
    LOAD_PRODUCTS_SUCCESS,
    SELECT_PRODUCT_SUCCESS,
    DESELECT_PRODUCT_SUCCESS
};
